version: "3.3"
services:

  db:
    hostname: mongo
    image: mongo:3.4
    restart: always
    ports:
      - "3001:27017"
    volumes:
      - db-data:/data/db
    networks:
      - sofie

  core:
    hostname: core
    image: sofietv/tv-automation-server-core:v1.0.0
    restart: always
    ports:
      - "3000:3000" # Same port as meteor uses by default
    environment:
      PORT: "3000"
      MONGO_URL: "mongodb://db:27017/meteor"
      ROOT_URL: "http://localhost:3000"
    networks:
      - sofie
    volumes:
      - snapshots:/mnt/snapshots
    depends_on:
      - db

  playout-gateway:
    image: sofietv/tv-automation-playout-gateway:develop
    restart: always
    command: yarn start -host core -port 3000
    networks:
      - sofie
    depends_on:
      - core

  ingest-gateway:
    image: superflytv/sofie-spreadsheet-gateway:develop
    # alternative mos gateway
    restart: always
    command: yarn start -host core -port 3000
    networks:
      - sofie
    depends_on:
      - core
  
# supertimeline:
#   image: ./supertimeline
#   restart: always
#  command: yarn start -host core -port 3000
#   networks:
#     - sofie
#  depends_on:
#     - core
      
  portainer:
   image: portainer/portainer
   restart: always
   ports:
     - "9000:9000"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data/portainer:/data

networks:
  sofie:

volumes:
  db-data:
  snapshots:
